// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_files/theater.proto

package com.tutorialspoint.theater;

public final class TheaterOuterClass {
  private TheaterOuterClass() {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public interface TheaterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Theater)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * 
     * @return The name.
     */
    java.lang.String getName();

    /**
     * <code>string name = 1;</code>
     * 
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString getNameBytes();

    /**
     * <code>string adderss = 2;</code>
     * 
     * @return The adderss.
     */
    java.lang.String getAdderss();

    /**
     * <code>string adderss = 2;</code>
     * 
     * @return The bytes for adderss.
     */
    com.google.protobuf.ByteString getAdderssBytes();
  }

  /**
   * Protobuf type {@code tutorial.Theater}
   */
  public static final class Theater extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.Theater)
      TheaterOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use Theater.newBuilder() to construct.
    private Theater(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private Theater() {
      name_ = "";
      adderss_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({ "unused" })
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Theater();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
      return this.unknownFields;
    }

    private Theater(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              adderss_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.tutorialspoint.theater.TheaterOuterClass.internal_static_tutorial_Theater_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
      return com.tutorialspoint.theater.TheaterOuterClass.internal_static_tutorial_Theater_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tutorialspoint.theater.TheaterOuterClass.Theater.class,
              com.tutorialspoint.theater.TheaterOuterClass.Theater.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;

    /**
     * <code>string name = 1;</code>
     * 
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }

    /**
     * <code>string name = 1;</code>
     * 
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
            (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDERSS_FIELD_NUMBER = 2;
    private volatile java.lang.Object adderss_;

    /**
     * <code>string adderss = 2;</code>
     * 
     * @return The adderss.
     */
    @java.lang.Override
    public java.lang.String getAdderss() {
      java.lang.Object ref = adderss_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        adderss_ = s;
        return s;
      }
    }

    /**
     * <code>string adderss = 2;</code>
     * 
     * @return The bytes for adderss.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getAdderssBytes() {
      java.lang.Object ref = adderss_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
            (java.lang.String) ref);
        adderss_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1)
        return true;
      if (isInitialized == 0)
        return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(adderss_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, adderss_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1)
        return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(adderss_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, adderss_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof com.tutorialspoint.theater.TheaterOuterClass.Theater)) {
        return super.equals(obj);
      }
      com.tutorialspoint.theater.TheaterOuterClass.Theater other = (com.tutorialspoint.theater.TheaterOuterClass.Theater) obj;

      if (!getName()
          .equals(other.getName()))
        return false;
      if (!getAdderss()
          .equals(other.getAdderss()))
        return false;
      if (!unknownFields.equals(other.unknownFields))
        return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + ADDERSS_FIELD_NUMBER;
      hash = (53 * hash) + getAdderss().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tutorialspoint.theater.TheaterOuterClass.Theater parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.tutorialspoint.theater.TheaterOuterClass.Theater parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.tutorialspoint.theater.TheaterOuterClass.Theater parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.tutorialspoint.theater.TheaterOuterClass.Theater parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.tutorialspoint.theater.TheaterOuterClass.Theater parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.tutorialspoint.theater.TheaterOuterClass.Theater parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.tutorialspoint.theater.TheaterOuterClass.Theater parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

    public static com.tutorialspoint.theater.TheaterOuterClass.Theater parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.tutorialspoint.theater.TheaterOuterClass.Theater parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.tutorialspoint.theater.TheaterOuterClass.Theater parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.tutorialspoint.theater.TheaterOuterClass.Theater parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

    public static com.tutorialspoint.theater.TheaterOuterClass.Theater parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.tutorialspoint.theater.TheaterOuterClass.Theater prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder()
          : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * Protobuf type {@code tutorial.Theater}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Theater)
        com.tutorialspoint.theater.TheaterOuterClass.TheaterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.tutorialspoint.theater.TheaterOuterClass.internal_static_tutorial_Theater_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return com.tutorialspoint.theater.TheaterOuterClass.internal_static_tutorial_Theater_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tutorialspoint.theater.TheaterOuterClass.Theater.class,
                com.tutorialspoint.theater.TheaterOuterClass.Theater.Builder.class);
      }

      // Construct using
      // com.tutorialspoint.greeting.TheaterOuterClass.Theater.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
        }
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        adderss_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return com.tutorialspoint.theater.TheaterOuterClass.internal_static_tutorial_Theater_descriptor;
      }

      @java.lang.Override
      public com.tutorialspoint.theater.TheaterOuterClass.Theater getDefaultInstanceForType() {
        return com.tutorialspoint.theater.TheaterOuterClass.Theater.getDefaultInstance();
      }

      @java.lang.Override
      public com.tutorialspoint.theater.TheaterOuterClass.Theater build() {
        com.tutorialspoint.theater.TheaterOuterClass.Theater result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tutorialspoint.theater.TheaterOuterClass.Theater buildPartial() {
        com.tutorialspoint.theater.TheaterOuterClass.Theater result = new com.tutorialspoint.theater.TheaterOuterClass.Theater(
            this);
        result.name_ = name_;
        result.adderss_ = adderss_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tutorialspoint.theater.TheaterOuterClass.Theater) {
          return mergeFrom((com.tutorialspoint.theater.TheaterOuterClass.Theater) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tutorialspoint.theater.TheaterOuterClass.Theater other) {
        if (other == com.tutorialspoint.theater.TheaterOuterClass.Theater.getDefaultInstance())
          return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getAdderss().isEmpty()) {
          adderss_ = other.adderss_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tutorialspoint.theater.TheaterOuterClass.Theater parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tutorialspoint.theater.TheaterOuterClass.Theater) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";

      /**
       * <code>string name = 1;</code>
       * 
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>string name = 1;</code>
       * 
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string name = 1;</code>
       * 
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        name_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string name = 1;</code>
       * 
       * @return This builder for chaining.
       */
      public Builder clearName() {

        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }

      /**
       * <code>string name = 1;</code>
       * 
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object adderss_ = "";

      /**
       * <code>string adderss = 2;</code>
       * 
       * @return The adderss.
       */
      public java.lang.String getAdderss() {
        java.lang.Object ref = adderss_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          adderss_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>string adderss = 2;</code>
       * 
       * @return The bytes for adderss.
       */
      public com.google.protobuf.ByteString getAdderssBytes() {
        java.lang.Object ref = adderss_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
          adderss_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string adderss = 2;</code>
       * 
       * @param value The adderss to set.
       * @return This builder for chaining.
       */
      public Builder setAdderss(
          java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        adderss_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string adderss = 2;</code>
       * 
       * @return This builder for chaining.
       */
      public Builder clearAdderss() {

        adderss_ = getDefaultInstance().getAdderss();
        onChanged();
        return this;
      }

      /**
       * <code>string adderss = 2;</code>
       * 
       * @param value The bytes for adderss to set.
       * @return This builder for chaining.
       */
      public Builder setAdderssBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        adderss_ = value;
        onChanged();
        return this;
      }

      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }

      // @@protoc_insertion_point(builder_scope:tutorial.Theater)
    }

    // @@protoc_insertion_point(class_scope:tutorial.Theater)
    private static final com.tutorialspoint.theater.TheaterOuterClass.Theater DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tutorialspoint.theater.TheaterOuterClass.Theater();
    }

    public static com.tutorialspoint.theater.TheaterOuterClass.Theater getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Theater> PARSER = new com.google.protobuf.AbstractParser<Theater>() {
      @java.lang.Override
      public Theater parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Theater(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Theater> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Theater> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tutorialspoint.theater.TheaterOuterClass.Theater getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface VistorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Vistor)
      com.google.protobuf.MessageOrBuilder {
  }

  /**
   * Protobuf type {@code tutorial.Vistor}
   */
  public static final class Vistor extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.Vistor)
      VistorOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use Vistor.newBuilder() to construct.
    private Vistor(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private Vistor() {
    }

    @java.lang.Override
    @SuppressWarnings({ "unused" })
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Vistor();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
      return this.unknownFields;
    }

    private Vistor(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.tutorialspoint.theater.TheaterOuterClass.internal_static_tutorial_Vistor_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
      return com.tutorialspoint.theater.TheaterOuterClass.internal_static_tutorial_Vistor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tutorialspoint.theater.TheaterOuterClass.Vistor.class,
              com.tutorialspoint.theater.TheaterOuterClass.Vistor.Builder.class);
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1)
        return true;
      if (isInitialized == 0)
        return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1)
        return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof com.tutorialspoint.theater.TheaterOuterClass.Vistor)) {
        return super.equals(obj);
      }
      com.tutorialspoint.theater.TheaterOuterClass.Vistor other = (com.tutorialspoint.theater.TheaterOuterClass.Vistor) obj;

      if (!unknownFields.equals(other.unknownFields))
        return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tutorialspoint.theater.TheaterOuterClass.Vistor parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.tutorialspoint.theater.TheaterOuterClass.Vistor parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.tutorialspoint.theater.TheaterOuterClass.Vistor parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.tutorialspoint.theater.TheaterOuterClass.Vistor parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.tutorialspoint.theater.TheaterOuterClass.Vistor parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.tutorialspoint.theater.TheaterOuterClass.Vistor parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.tutorialspoint.theater.TheaterOuterClass.Vistor parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

    public static com.tutorialspoint.theater.TheaterOuterClass.Vistor parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.tutorialspoint.theater.TheaterOuterClass.Vistor parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.tutorialspoint.theater.TheaterOuterClass.Vistor parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.tutorialspoint.theater.TheaterOuterClass.Vistor parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

    public static com.tutorialspoint.theater.TheaterOuterClass.Vistor parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.tutorialspoint.theater.TheaterOuterClass.Vistor prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder()
          : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * Protobuf type {@code tutorial.Vistor}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Vistor)
        com.tutorialspoint.theater.TheaterOuterClass.VistorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.tutorialspoint.theater.TheaterOuterClass.internal_static_tutorial_Vistor_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return com.tutorialspoint.theater.TheaterOuterClass.internal_static_tutorial_Vistor_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tutorialspoint.theater.TheaterOuterClass.Vistor.class,
                com.tutorialspoint.theater.TheaterOuterClass.Vistor.Builder.class);
      }

      // Construct using
      // com.tutorialspoint.greeting.TheaterOuterClass.Vistor.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
        }
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return com.tutorialspoint.theater.TheaterOuterClass.internal_static_tutorial_Vistor_descriptor;
      }

      @java.lang.Override
      public com.tutorialspoint.theater.TheaterOuterClass.Vistor getDefaultInstanceForType() {
        return com.tutorialspoint.theater.TheaterOuterClass.Vistor.getDefaultInstance();
      }

      @java.lang.Override
      public com.tutorialspoint.theater.TheaterOuterClass.Vistor build() {
        com.tutorialspoint.theater.TheaterOuterClass.Vistor result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tutorialspoint.theater.TheaterOuterClass.Vistor buildPartial() {
        com.tutorialspoint.theater.TheaterOuterClass.Vistor result = new com.tutorialspoint.theater.TheaterOuterClass.Vistor(
            this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tutorialspoint.theater.TheaterOuterClass.Vistor) {
          return mergeFrom((com.tutorialspoint.theater.TheaterOuterClass.Vistor) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tutorialspoint.theater.TheaterOuterClass.Vistor other) {
        if (other == com.tutorialspoint.theater.TheaterOuterClass.Vistor.getDefaultInstance())
          return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tutorialspoint.theater.TheaterOuterClass.Vistor parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tutorialspoint.theater.TheaterOuterClass.Vistor) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }

      // @@protoc_insertion_point(builder_scope:tutorial.Vistor)
    }

    // @@protoc_insertion_point(class_scope:tutorial.Vistor)
    private static final com.tutorialspoint.theater.TheaterOuterClass.Vistor DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tutorialspoint.theater.TheaterOuterClass.Vistor();
    }

    public static com.tutorialspoint.theater.TheaterOuterClass.Vistor getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Vistor> PARSER = new com.google.protobuf.AbstractParser<Vistor>() {
      @java.lang.Override
      public Vistor parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Vistor(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Vistor> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Vistor> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tutorialspoint.theater.TheaterOuterClass.Vistor getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor internal_static_tutorial_Theater_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_tutorial_Theater_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor internal_static_tutorial_Vistor_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_tutorial_Vistor_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
  static {
    java.lang.String[] descriptorData = {
        "\n\031proto_files/theater.proto\022\010tutorial\"(\n" +
            "\007Theater\022\014\n\004name\030\001 \001(\t\022\017\n\007adderss\030\002 \001(\t\"" +
            "\010\n\006VistorB\035\n\033com.tutorialspoint.greeting" +
            "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
        .internalBuildGeneratedFileFrom(descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
            });
    internal_static_tutorial_Theater_descriptor = getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_Theater_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Theater_descriptor,
        new java.lang.String[] { "Name", "Adderss", });
    internal_static_tutorial_Vistor_descriptor = getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_Vistor_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Vistor_descriptor,
        new java.lang.String[] {});
  }

  // @@protoc_insertion_point(outer_class_scope)
}
