// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_files/theater.proto

package com.tutorialspoint.theater;

public final class TheaterOuterClass {
  private TheaterOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TheaterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Theater)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string adderss = 2;</code>
     * @return The adderss.
     */
    java.lang.String getAdderss();
    /**
     * <code>string adderss = 2;</code>
     * @return The bytes for adderss.
     */
    com.google.protobuf.ByteString
        getAdderssBytes();

    /**
     * <code>int32 total_capacity = 3;</code>
     * @return The totalCapacity.
     */
    int getTotalCapacity();

    /**
     * <code>int64 mobile = 4;</code>
     * @return The mobile.
     */
    long getMobile();

    /**
     * <code>float base_ticket_price = 5;</code>
     * @return The baseTicketPrice.
     */
    float getBaseTicketPrice();

    /**
     * <code>bool drive_in = 6;</code>
     * @return The driveIn.
     */
    boolean getDriveIn();

    /**
     * <code>.tutorial.Theater.PAYMENT_SYSTEM payment = 7;</code>
     * @return The enum numeric value on the wire for payment.
     */
    int getPaymentValue();
    /**
     * <code>.tutorial.Theater.PAYMENT_SYSTEM payment = 7;</code>
     * @return The payment.
     */
    com.tutorialspoint.theater.TheaterOuterClass.Theater.PAYMENT_SYSTEM getPayment();

    /**
     * <code>repeated string snacks = 8;</code>
     * @return A list containing the snacks.
     */
    java.util.List<java.lang.String>
        getSnacksList();
    /**
     * <code>repeated string snacks = 8;</code>
     * @return The count of snacks.
     */
    int getSnacksCount();
    /**
     * <code>repeated string snacks = 8;</code>
     * @param index The index of the element to return.
     * @return The snacks at the given index.
     */
    java.lang.String getSnacks(int index);
    /**
     * <code>repeated string snacks = 8;</code>
     * @param index The index of the value to return.
     * @return The bytes of the snacks at the given index.
     */
    com.google.protobuf.ByteString
        getSnacksBytes(int index);
  }
  /**
   * Protobuf type {@code tutorial.Theater}
   */
  public static final class Theater extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.Theater)
      TheaterOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Theater.newBuilder() to construct.
    private Theater(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Theater() {
      name_ = "";
      adderss_ = "";
      payment_ = 0;
      snacks_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Theater();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Theater(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              adderss_ = s;
              break;
            }
            case 24: {

              totalCapacity_ = input.readInt32();
              break;
            }
            case 32: {

              mobile_ = input.readInt64();
              break;
            }
            case 45: {

              baseTicketPrice_ = input.readFloat();
              break;
            }
            case 48: {

              driveIn_ = input.readBool();
              break;
            }
            case 56: {
              int rawValue = input.readEnum();

              payment_ = rawValue;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                snacks_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              snacks_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          snacks_ = snacks_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tutorialspoint.theater.TheaterOuterClass.internal_static_tutorial_Theater_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tutorialspoint.theater.TheaterOuterClass.internal_static_tutorial_Theater_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tutorialspoint.theater.TheaterOuterClass.Theater.class, com.tutorialspoint.theater.TheaterOuterClass.Theater.Builder.class);
    }

    /**
     * Protobuf enum {@code tutorial.Theater.PAYMENT_SYSTEM}
     */
    public enum PAYMENT_SYSTEM
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CASH = 0;</code>
       */
      CASH(0),
      /**
       * <code>CREDIT_CARD = 1;</code>
       */
      CREDIT_CARD(1),
      /**
       * <code>DEBIT_CARD = 2;</code>
       */
      DEBIT_CARD(2),
      /**
       * <code>APP = 3;</code>
       */
      APP(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>CASH = 0;</code>
       */
      public static final int CASH_VALUE = 0;
      /**
       * <code>CREDIT_CARD = 1;</code>
       */
      public static final int CREDIT_CARD_VALUE = 1;
      /**
       * <code>DEBIT_CARD = 2;</code>
       */
      public static final int DEBIT_CARD_VALUE = 2;
      /**
       * <code>APP = 3;</code>
       */
      public static final int APP_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PAYMENT_SYSTEM valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static PAYMENT_SYSTEM forNumber(int value) {
        switch (value) {
          case 0: return CASH;
          case 1: return CREDIT_CARD;
          case 2: return DEBIT_CARD;
          case 3: return APP;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PAYMENT_SYSTEM>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          PAYMENT_SYSTEM> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PAYMENT_SYSTEM>() {
              public PAYMENT_SYSTEM findValueByNumber(int number) {
                return PAYMENT_SYSTEM.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.tutorialspoint.theater.TheaterOuterClass.Theater.getDescriptor().getEnumTypes().get(0);
      }

      private static final PAYMENT_SYSTEM[] VALUES = values();

      public static PAYMENT_SYSTEM valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private PAYMENT_SYSTEM(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:tutorial.Theater.PAYMENT_SYSTEM)
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDERSS_FIELD_NUMBER = 2;
    private volatile java.lang.Object adderss_;
    /**
     * <code>string adderss = 2;</code>
     * @return The adderss.
     */
    @java.lang.Override
    public java.lang.String getAdderss() {
      java.lang.Object ref = adderss_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        adderss_ = s;
        return s;
      }
    }
    /**
     * <code>string adderss = 2;</code>
     * @return The bytes for adderss.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAdderssBytes() {
      java.lang.Object ref = adderss_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        adderss_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOTAL_CAPACITY_FIELD_NUMBER = 3;
    private int totalCapacity_;
    /**
     * <code>int32 total_capacity = 3;</code>
     * @return The totalCapacity.
     */
    @java.lang.Override
    public int getTotalCapacity() {
      return totalCapacity_;
    }

    public static final int MOBILE_FIELD_NUMBER = 4;
    private long mobile_;
    /**
     * <code>int64 mobile = 4;</code>
     * @return The mobile.
     */
    @java.lang.Override
    public long getMobile() {
      return mobile_;
    }

    public static final int BASE_TICKET_PRICE_FIELD_NUMBER = 5;
    private float baseTicketPrice_;
    /**
     * <code>float base_ticket_price = 5;</code>
     * @return The baseTicketPrice.
     */
    @java.lang.Override
    public float getBaseTicketPrice() {
      return baseTicketPrice_;
    }

    public static final int DRIVE_IN_FIELD_NUMBER = 6;
    private boolean driveIn_;
    /**
     * <code>bool drive_in = 6;</code>
     * @return The driveIn.
     */
    @java.lang.Override
    public boolean getDriveIn() {
      return driveIn_;
    }

    public static final int PAYMENT_FIELD_NUMBER = 7;
    private int payment_;
    /**
     * <code>.tutorial.Theater.PAYMENT_SYSTEM payment = 7;</code>
     * @return The enum numeric value on the wire for payment.
     */
    @java.lang.Override public int getPaymentValue() {
      return payment_;
    }
    /**
     * <code>.tutorial.Theater.PAYMENT_SYSTEM payment = 7;</code>
     * @return The payment.
     */
    @java.lang.Override public com.tutorialspoint.theater.TheaterOuterClass.Theater.PAYMENT_SYSTEM getPayment() {
      @SuppressWarnings("deprecation")
      com.tutorialspoint.theater.TheaterOuterClass.Theater.PAYMENT_SYSTEM result = com.tutorialspoint.theater.TheaterOuterClass.Theater.PAYMENT_SYSTEM.valueOf(payment_);
      return result == null ? com.tutorialspoint.theater.TheaterOuterClass.Theater.PAYMENT_SYSTEM.UNRECOGNIZED : result;
    }

    public static final int SNACKS_FIELD_NUMBER = 8;
    private com.google.protobuf.LazyStringList snacks_;
    /**
     * <code>repeated string snacks = 8;</code>
     * @return A list containing the snacks.
     */
    public com.google.protobuf.ProtocolStringList
        getSnacksList() {
      return snacks_;
    }
    /**
     * <code>repeated string snacks = 8;</code>
     * @return The count of snacks.
     */
    public int getSnacksCount() {
      return snacks_.size();
    }
    /**
     * <code>repeated string snacks = 8;</code>
     * @param index The index of the element to return.
     * @return The snacks at the given index.
     */
    public java.lang.String getSnacks(int index) {
      return snacks_.get(index);
    }
    /**
     * <code>repeated string snacks = 8;</code>
     * @param index The index of the value to return.
     * @return The bytes of the snacks at the given index.
     */
    public com.google.protobuf.ByteString
        getSnacksBytes(int index) {
      return snacks_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(adderss_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, adderss_);
      }
      if (totalCapacity_ != 0) {
        output.writeInt32(3, totalCapacity_);
      }
      if (mobile_ != 0L) {
        output.writeInt64(4, mobile_);
      }
      if (java.lang.Float.floatToRawIntBits(baseTicketPrice_) != 0) {
        output.writeFloat(5, baseTicketPrice_);
      }
      if (driveIn_ != false) {
        output.writeBool(6, driveIn_);
      }
      if (payment_ != com.tutorialspoint.theater.TheaterOuterClass.Theater.PAYMENT_SYSTEM.CASH.getNumber()) {
        output.writeEnum(7, payment_);
      }
      for (int i = 0; i < snacks_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, snacks_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(adderss_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, adderss_);
      }
      if (totalCapacity_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, totalCapacity_);
      }
      if (mobile_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, mobile_);
      }
      if (java.lang.Float.floatToRawIntBits(baseTicketPrice_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, baseTicketPrice_);
      }
      if (driveIn_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, driveIn_);
      }
      if (payment_ != com.tutorialspoint.theater.TheaterOuterClass.Theater.PAYMENT_SYSTEM.CASH.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, payment_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < snacks_.size(); i++) {
          dataSize += computeStringSizeNoTag(snacks_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getSnacksList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tutorialspoint.theater.TheaterOuterClass.Theater)) {
        return super.equals(obj);
      }
      com.tutorialspoint.theater.TheaterOuterClass.Theater other = (com.tutorialspoint.theater.TheaterOuterClass.Theater) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getAdderss()
          .equals(other.getAdderss())) return false;
      if (getTotalCapacity()
          != other.getTotalCapacity()) return false;
      if (getMobile()
          != other.getMobile()) return false;
      if (java.lang.Float.floatToIntBits(getBaseTicketPrice())
          != java.lang.Float.floatToIntBits(
              other.getBaseTicketPrice())) return false;
      if (getDriveIn()
          != other.getDriveIn()) return false;
      if (payment_ != other.payment_) return false;
      if (!getSnacksList()
          .equals(other.getSnacksList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + ADDERSS_FIELD_NUMBER;
      hash = (53 * hash) + getAdderss().hashCode();
      hash = (37 * hash) + TOTAL_CAPACITY_FIELD_NUMBER;
      hash = (53 * hash) + getTotalCapacity();
      hash = (37 * hash) + MOBILE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMobile());
      hash = (37 * hash) + BASE_TICKET_PRICE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getBaseTicketPrice());
      hash = (37 * hash) + DRIVE_IN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getDriveIn());
      hash = (37 * hash) + PAYMENT_FIELD_NUMBER;
      hash = (53 * hash) + payment_;
      if (getSnacksCount() > 0) {
        hash = (37 * hash) + SNACKS_FIELD_NUMBER;
        hash = (53 * hash) + getSnacksList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tutorialspoint.theater.TheaterOuterClass.Theater parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tutorialspoint.theater.TheaterOuterClass.Theater parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tutorialspoint.theater.TheaterOuterClass.Theater parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tutorialspoint.theater.TheaterOuterClass.Theater parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tutorialspoint.theater.TheaterOuterClass.Theater parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tutorialspoint.theater.TheaterOuterClass.Theater parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tutorialspoint.theater.TheaterOuterClass.Theater parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tutorialspoint.theater.TheaterOuterClass.Theater parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tutorialspoint.theater.TheaterOuterClass.Theater parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tutorialspoint.theater.TheaterOuterClass.Theater parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tutorialspoint.theater.TheaterOuterClass.Theater parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tutorialspoint.theater.TheaterOuterClass.Theater parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tutorialspoint.theater.TheaterOuterClass.Theater prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Theater}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Theater)
        com.tutorialspoint.theater.TheaterOuterClass.TheaterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tutorialspoint.theater.TheaterOuterClass.internal_static_tutorial_Theater_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tutorialspoint.theater.TheaterOuterClass.internal_static_tutorial_Theater_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tutorialspoint.theater.TheaterOuterClass.Theater.class, com.tutorialspoint.theater.TheaterOuterClass.Theater.Builder.class);
      }

      // Construct using com.tutorialspoint.theater.TheaterOuterClass.Theater.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        adderss_ = "";

        totalCapacity_ = 0;

        mobile_ = 0L;

        baseTicketPrice_ = 0F;

        driveIn_ = false;

        payment_ = 0;

        snacks_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tutorialspoint.theater.TheaterOuterClass.internal_static_tutorial_Theater_descriptor;
      }

      @java.lang.Override
      public com.tutorialspoint.theater.TheaterOuterClass.Theater getDefaultInstanceForType() {
        return com.tutorialspoint.theater.TheaterOuterClass.Theater.getDefaultInstance();
      }

      @java.lang.Override
      public com.tutorialspoint.theater.TheaterOuterClass.Theater build() {
        com.tutorialspoint.theater.TheaterOuterClass.Theater result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tutorialspoint.theater.TheaterOuterClass.Theater buildPartial() {
        com.tutorialspoint.theater.TheaterOuterClass.Theater result = new com.tutorialspoint.theater.TheaterOuterClass.Theater(this);
        int from_bitField0_ = bitField0_;
        result.name_ = name_;
        result.adderss_ = adderss_;
        result.totalCapacity_ = totalCapacity_;
        result.mobile_ = mobile_;
        result.baseTicketPrice_ = baseTicketPrice_;
        result.driveIn_ = driveIn_;
        result.payment_ = payment_;
        if (((bitField0_ & 0x00000001) != 0)) {
          snacks_ = snacks_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.snacks_ = snacks_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tutorialspoint.theater.TheaterOuterClass.Theater) {
          return mergeFrom((com.tutorialspoint.theater.TheaterOuterClass.Theater)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tutorialspoint.theater.TheaterOuterClass.Theater other) {
        if (other == com.tutorialspoint.theater.TheaterOuterClass.Theater.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getAdderss().isEmpty()) {
          adderss_ = other.adderss_;
          onChanged();
        }
        if (other.getTotalCapacity() != 0) {
          setTotalCapacity(other.getTotalCapacity());
        }
        if (other.getMobile() != 0L) {
          setMobile(other.getMobile());
        }
        if (other.getBaseTicketPrice() != 0F) {
          setBaseTicketPrice(other.getBaseTicketPrice());
        }
        if (other.getDriveIn() != false) {
          setDriveIn(other.getDriveIn());
        }
        if (other.payment_ != 0) {
          setPaymentValue(other.getPaymentValue());
        }
        if (!other.snacks_.isEmpty()) {
          if (snacks_.isEmpty()) {
            snacks_ = other.snacks_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSnacksIsMutable();
            snacks_.addAll(other.snacks_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tutorialspoint.theater.TheaterOuterClass.Theater parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tutorialspoint.theater.TheaterOuterClass.Theater) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object adderss_ = "";
      /**
       * <code>string adderss = 2;</code>
       * @return The adderss.
       */
      public java.lang.String getAdderss() {
        java.lang.Object ref = adderss_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          adderss_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string adderss = 2;</code>
       * @return The bytes for adderss.
       */
      public com.google.protobuf.ByteString
          getAdderssBytes() {
        java.lang.Object ref = adderss_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          adderss_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string adderss = 2;</code>
       * @param value The adderss to set.
       * @return This builder for chaining.
       */
      public Builder setAdderss(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        adderss_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string adderss = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAdderss() {
        
        adderss_ = getDefaultInstance().getAdderss();
        onChanged();
        return this;
      }
      /**
       * <code>string adderss = 2;</code>
       * @param value The bytes for adderss to set.
       * @return This builder for chaining.
       */
      public Builder setAdderssBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        adderss_ = value;
        onChanged();
        return this;
      }

      private int totalCapacity_ ;
      /**
       * <code>int32 total_capacity = 3;</code>
       * @return The totalCapacity.
       */
      @java.lang.Override
      public int getTotalCapacity() {
        return totalCapacity_;
      }
      /**
       * <code>int32 total_capacity = 3;</code>
       * @param value The totalCapacity to set.
       * @return This builder for chaining.
       */
      public Builder setTotalCapacity(int value) {
        
        totalCapacity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 total_capacity = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalCapacity() {
        
        totalCapacity_ = 0;
        onChanged();
        return this;
      }

      private long mobile_ ;
      /**
       * <code>int64 mobile = 4;</code>
       * @return The mobile.
       */
      @java.lang.Override
      public long getMobile() {
        return mobile_;
      }
      /**
       * <code>int64 mobile = 4;</code>
       * @param value The mobile to set.
       * @return This builder for chaining.
       */
      public Builder setMobile(long value) {
        
        mobile_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 mobile = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMobile() {
        
        mobile_ = 0L;
        onChanged();
        return this;
      }

      private float baseTicketPrice_ ;
      /**
       * <code>float base_ticket_price = 5;</code>
       * @return The baseTicketPrice.
       */
      @java.lang.Override
      public float getBaseTicketPrice() {
        return baseTicketPrice_;
      }
      /**
       * <code>float base_ticket_price = 5;</code>
       * @param value The baseTicketPrice to set.
       * @return This builder for chaining.
       */
      public Builder setBaseTicketPrice(float value) {
        
        baseTicketPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float base_ticket_price = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearBaseTicketPrice() {
        
        baseTicketPrice_ = 0F;
        onChanged();
        return this;
      }

      private boolean driveIn_ ;
      /**
       * <code>bool drive_in = 6;</code>
       * @return The driveIn.
       */
      @java.lang.Override
      public boolean getDriveIn() {
        return driveIn_;
      }
      /**
       * <code>bool drive_in = 6;</code>
       * @param value The driveIn to set.
       * @return This builder for chaining.
       */
      public Builder setDriveIn(boolean value) {
        
        driveIn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool drive_in = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearDriveIn() {
        
        driveIn_ = false;
        onChanged();
        return this;
      }

      private int payment_ = 0;
      /**
       * <code>.tutorial.Theater.PAYMENT_SYSTEM payment = 7;</code>
       * @return The enum numeric value on the wire for payment.
       */
      @java.lang.Override public int getPaymentValue() {
        return payment_;
      }
      /**
       * <code>.tutorial.Theater.PAYMENT_SYSTEM payment = 7;</code>
       * @param value The enum numeric value on the wire for payment to set.
       * @return This builder for chaining.
       */
      public Builder setPaymentValue(int value) {
        
        payment_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.tutorial.Theater.PAYMENT_SYSTEM payment = 7;</code>
       * @return The payment.
       */
      @java.lang.Override
      public com.tutorialspoint.theater.TheaterOuterClass.Theater.PAYMENT_SYSTEM getPayment() {
        @SuppressWarnings("deprecation")
        com.tutorialspoint.theater.TheaterOuterClass.Theater.PAYMENT_SYSTEM result = com.tutorialspoint.theater.TheaterOuterClass.Theater.PAYMENT_SYSTEM.valueOf(payment_);
        return result == null ? com.tutorialspoint.theater.TheaterOuterClass.Theater.PAYMENT_SYSTEM.UNRECOGNIZED : result;
      }
      /**
       * <code>.tutorial.Theater.PAYMENT_SYSTEM payment = 7;</code>
       * @param value The payment to set.
       * @return This builder for chaining.
       */
      public Builder setPayment(com.tutorialspoint.theater.TheaterOuterClass.Theater.PAYMENT_SYSTEM value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        payment_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.tutorial.Theater.PAYMENT_SYSTEM payment = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearPayment() {
        
        payment_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList snacks_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureSnacksIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          snacks_ = new com.google.protobuf.LazyStringArrayList(snacks_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string snacks = 8;</code>
       * @return A list containing the snacks.
       */
      public com.google.protobuf.ProtocolStringList
          getSnacksList() {
        return snacks_.getUnmodifiableView();
      }
      /**
       * <code>repeated string snacks = 8;</code>
       * @return The count of snacks.
       */
      public int getSnacksCount() {
        return snacks_.size();
      }
      /**
       * <code>repeated string snacks = 8;</code>
       * @param index The index of the element to return.
       * @return The snacks at the given index.
       */
      public java.lang.String getSnacks(int index) {
        return snacks_.get(index);
      }
      /**
       * <code>repeated string snacks = 8;</code>
       * @param index The index of the value to return.
       * @return The bytes of the snacks at the given index.
       */
      public com.google.protobuf.ByteString
          getSnacksBytes(int index) {
        return snacks_.getByteString(index);
      }
      /**
       * <code>repeated string snacks = 8;</code>
       * @param index The index to set the value at.
       * @param value The snacks to set.
       * @return This builder for chaining.
       */
      public Builder setSnacks(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSnacksIsMutable();
        snacks_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string snacks = 8;</code>
       * @param value The snacks to add.
       * @return This builder for chaining.
       */
      public Builder addSnacks(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSnacksIsMutable();
        snacks_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string snacks = 8;</code>
       * @param values The snacks to add.
       * @return This builder for chaining.
       */
      public Builder addAllSnacks(
          java.lang.Iterable<java.lang.String> values) {
        ensureSnacksIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, snacks_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string snacks = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearSnacks() {
        snacks_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string snacks = 8;</code>
       * @param value The bytes of the snacks to add.
       * @return This builder for chaining.
       */
      public Builder addSnacksBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureSnacksIsMutable();
        snacks_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.Theater)
    }

    // @@protoc_insertion_point(class_scope:tutorial.Theater)
    private static final com.tutorialspoint.theater.TheaterOuterClass.Theater DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tutorialspoint.theater.TheaterOuterClass.Theater();
    }

    public static com.tutorialspoint.theater.TheaterOuterClass.Theater getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Theater>
        PARSER = new com.google.protobuf.AbstractParser<Theater>() {
      @java.lang.Override
      public Theater parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Theater(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Theater> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Theater> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tutorialspoint.theater.TheaterOuterClass.Theater getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface VistorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Vistor)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code tutorial.Vistor}
   */
  public static final class Vistor extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.Vistor)
      VistorOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Vistor.newBuilder() to construct.
    private Vistor(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Vistor() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Vistor();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Vistor(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tutorialspoint.theater.TheaterOuterClass.internal_static_tutorial_Vistor_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tutorialspoint.theater.TheaterOuterClass.internal_static_tutorial_Vistor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tutorialspoint.theater.TheaterOuterClass.Vistor.class, com.tutorialspoint.theater.TheaterOuterClass.Vistor.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tutorialspoint.theater.TheaterOuterClass.Vistor)) {
        return super.equals(obj);
      }
      com.tutorialspoint.theater.TheaterOuterClass.Vistor other = (com.tutorialspoint.theater.TheaterOuterClass.Vistor) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tutorialspoint.theater.TheaterOuterClass.Vistor parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tutorialspoint.theater.TheaterOuterClass.Vistor parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tutorialspoint.theater.TheaterOuterClass.Vistor parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tutorialspoint.theater.TheaterOuterClass.Vistor parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tutorialspoint.theater.TheaterOuterClass.Vistor parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tutorialspoint.theater.TheaterOuterClass.Vistor parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tutorialspoint.theater.TheaterOuterClass.Vistor parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tutorialspoint.theater.TheaterOuterClass.Vistor parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tutorialspoint.theater.TheaterOuterClass.Vistor parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tutorialspoint.theater.TheaterOuterClass.Vistor parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tutorialspoint.theater.TheaterOuterClass.Vistor parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tutorialspoint.theater.TheaterOuterClass.Vistor parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tutorialspoint.theater.TheaterOuterClass.Vistor prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Vistor}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Vistor)
        com.tutorialspoint.theater.TheaterOuterClass.VistorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tutorialspoint.theater.TheaterOuterClass.internal_static_tutorial_Vistor_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tutorialspoint.theater.TheaterOuterClass.internal_static_tutorial_Vistor_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tutorialspoint.theater.TheaterOuterClass.Vistor.class, com.tutorialspoint.theater.TheaterOuterClass.Vistor.Builder.class);
      }

      // Construct using com.tutorialspoint.theater.TheaterOuterClass.Vistor.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tutorialspoint.theater.TheaterOuterClass.internal_static_tutorial_Vistor_descriptor;
      }

      @java.lang.Override
      public com.tutorialspoint.theater.TheaterOuterClass.Vistor getDefaultInstanceForType() {
        return com.tutorialspoint.theater.TheaterOuterClass.Vistor.getDefaultInstance();
      }

      @java.lang.Override
      public com.tutorialspoint.theater.TheaterOuterClass.Vistor build() {
        com.tutorialspoint.theater.TheaterOuterClass.Vistor result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tutorialspoint.theater.TheaterOuterClass.Vistor buildPartial() {
        com.tutorialspoint.theater.TheaterOuterClass.Vistor result = new com.tutorialspoint.theater.TheaterOuterClass.Vistor(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tutorialspoint.theater.TheaterOuterClass.Vistor) {
          return mergeFrom((com.tutorialspoint.theater.TheaterOuterClass.Vistor)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tutorialspoint.theater.TheaterOuterClass.Vistor other) {
        if (other == com.tutorialspoint.theater.TheaterOuterClass.Vistor.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tutorialspoint.theater.TheaterOuterClass.Vistor parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tutorialspoint.theater.TheaterOuterClass.Vistor) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.Vistor)
    }

    // @@protoc_insertion_point(class_scope:tutorial.Vistor)
    private static final com.tutorialspoint.theater.TheaterOuterClass.Vistor DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tutorialspoint.theater.TheaterOuterClass.Vistor();
    }

    public static com.tutorialspoint.theater.TheaterOuterClass.Vistor getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Vistor>
        PARSER = new com.google.protobuf.AbstractParser<Vistor>() {
      @java.lang.Override
      public Vistor parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Vistor(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Vistor> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Vistor> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tutorialspoint.theater.TheaterOuterClass.Vistor getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Theater_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Theater_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Vistor_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Vistor_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031proto_files/theater.proto\022\010tutorial\"\206\002" +
      "\n\007Theater\022\014\n\004name\030\001 \001(\t\022\017\n\007adderss\030\002 \001(\t" +
      "\022\026\n\016total_capacity\030\003 \001(\005\022\016\n\006mobile\030\004 \001(\003" +
      "\022\031\n\021base_ticket_price\030\005 \001(\002\022\020\n\010drive_in\030" +
      "\006 \001(\010\0221\n\007payment\030\007 \001(\0162 .tutorial.Theate" +
      "r.PAYMENT_SYSTEM\022\016\n\006snacks\030\010 \003(\t\"D\n\016PAYM" +
      "ENT_SYSTEM\022\010\n\004CASH\020\000\022\017\n\013CREDIT_CARD\020\001\022\016\n" +
      "\nDEBIT_CARD\020\002\022\007\n\003APP\020\003\"\010\n\006VistorB\034\n\032com." +
      "tutorialspoint.theaterb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_Theater_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_Theater_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Theater_descriptor,
        new java.lang.String[] { "Name", "Adderss", "TotalCapacity", "Mobile", "BaseTicketPrice", "DriveIn", "Payment", "Snacks", });
    internal_static_tutorial_Vistor_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_Vistor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Vistor_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
